### ISSUE TITLE
DB server setting

### ISSUE THREAD

**Issue by taejin0323** [InSSAFY/InIT_SpringBoot#15]
## Description
백엔드 서버에 사용되는 DB 설정

## To-Do
- [ ] DB server 선정
- [ ] SpringBoot와 연동
- [ ] 기본적인 ERD 설계
- [ ] 매우 기본적인 CRUD 테스트

## Discussion

- #11
