### ISSUE TITLE
🌱 [FEATURE] Hide jwt key as a variable in application.yml file

### ISSUE THREAD

**Issue by wkdalsgh192** [InSSAFY/InIT_SpringBoot#40]
## Description
현재 JWT 키가 소스 코드 상에 구현되어있는 데 공개되는 경우 보안 상 위험이 있기 때문에 숨겨야 합니다. 이를 위해 EC2 인스턴스 상에 application.yml 파일을 만들어 해당 파일 내 환경 변수로 등록하고자 합니다.

## To-Do
- [x] application.yml 파일 만들기
- [x] JWT 키 코드 변경
- [x] 작동 여부 테스트
